window.metricRecords = [
  {
    metric: "Net revenue retention",
    team: "Sales",
    owner: "Revenue Ops",
    system: "Warehouse",
    dashboard: "Executive scorecard",
    freshnessHours: 7,
    definitionScore: 94,
    usage30d: 186,
    variancePct: 1.1,
    excelMismatchRate: 0.4,
    issueCount: 1,
    decisionCriticality: 5
  },
  {
    metric: "Qualified pipeline coverage",
    team: "Sales",
    owner: "Sales Analytics",
    system: "CRM",
    dashboard: "Pipeline weekly review",
    freshnessHours: 11,
    definitionScore: 88,
    usage30d: 151,
    variancePct: 2.7,
    excelMismatchRate: 1.1,
    issueCount: 2,
    decisionCriticality: 5
  },
  {
    metric: "Stage conversion rate",
    team: "Sales",
    owner: "Unassigned",
    system: "CRM",
    dashboard: "Pipeline weekly review",
    freshnessHours: 28,
    definitionScore: 72,
    usage30d: 118,
    variancePct: 4.6,
    excelMismatchRate: 3.8,
    issueCount: 5,
    decisionCriticality: 4
  },
  {
    metric: "Average discount depth",
    team: "Sales",
    owner: "Finance BI",
    system: "Billing",
    dashboard: "Deal desk monitor",
    freshnessHours: 17,
    definitionScore: 81,
    usage30d: 83,
    variancePct: 2.3,
    excelMismatchRate: 4.9,
    issueCount: 4,
    decisionCriticality: 3
  },
  {
    metric: "Activation rate",
    team: "Product",
    owner: "Product Analytics",
    system: "Event stream",
    dashboard: "Product adoption hub",
    freshnessHours: 9,
    definitionScore: 91,
    usage30d: 174,
    variancePct: 1.8,
    excelMismatchRate: 0.7,
    issueCount: 1,
    decisionCriticality: 5
  },
  {
    metric: "Feature adoption rate",
    team: "Product",
    owner: "Product Analytics",
    system: "Event stream",
    dashboard: "Product adoption hub",
    freshnessHours: 21,
    definitionScore: 79,
    usage30d: 132,
    variancePct: 3.2,
    excelMismatchRate: 1.9,
    issueCount: 3,
    decisionCriticality: 4
  },
  {
    metric: "Trial to paid conversion",
    team: "Product",
    owner: "Growth Analytics",
    system: "Warehouse",
    dashboard: "Growth funnel",
    freshnessHours: 31,
    definitionScore: 74,
    usage30d: 143,
    variancePct: 5.1,
    excelMismatchRate: 4.2,
    issueCount: 6,
    decisionCriticality: 5
  },
  {
    metric: "In-app engagement depth",
    team: "Product",
    owner: "Unassigned",
    system: "Event stream",
    dashboard: "Product adoption hub",
    freshnessHours: 42,
    definitionScore: 68,
    usage30d: 77,
    variancePct: 6.4,
    excelMismatchRate: 5.6,
    issueCount: 7,
    decisionCriticality: 3
  },
  {
    metric: "Marketing qualified leads",
    team: "Marketing",
    owner: "Demand Gen Ops",
    system: "Marketing automation",
    dashboard: "Demand performance",
    freshnessHours: 13,
    definitionScore: 86,
    usage30d: 129,
    variancePct: 2.2,
    excelMismatchRate: 1.4,
    issueCount: 2,
    decisionCriticality: 4
  },
  {
    metric: "Campaign sourced pipeline",
    team: "Marketing",
    owner: "Demand Gen Ops",
    system: "CRM",
    dashboard: "Demand performance",
    freshnessHours: 29,
    definitionScore: 76,
    usage30d: 112,
    variancePct: 4.7,
    excelMismatchRate: 4.4,
    issueCount: 5,
    decisionCriticality: 4
  },
  {
    metric: "Paid acquisition CAC",
    team: "Marketing",
    owner: "Finance BI",
    system: "Ads platform",
    dashboard: "Spend efficiency",
    freshnessHours: 35,
    definitionScore: 71,
    usage30d: 94,
    variancePct: 6.8,
    excelMismatchRate: 6.2,
    issueCount: 6,
    decisionCriticality: 5
  },
  {
    metric: "Email nurture conversion",
    team: "Marketing",
    owner: "Lifecycle Marketing",
    system: "Marketing automation",
    dashboard: "Lifecycle monitor",
    freshnessHours: 19,
    definitionScore: 83,
    usage30d: 71,
    variancePct: 2.9,
    excelMismatchRate: 2.1,
    issueCount: 2,
    decisionCriticality: 2
  },
  {
    metric: "Gross margin",
    team: "Finance",
    owner: "Finance BI",
    system: "ERP",
    dashboard: "Board packet",
    freshnessHours: 8,
    definitionScore: 96,
    usage30d: 168,
    variancePct: 0.9,
    excelMismatchRate: 0.3,
    issueCount: 0,
    decisionCriticality: 5
  },
  {
    metric: "Budget variance",
    team: "Finance",
    owner: "FP&A",
    system: "ERP",
    dashboard: "Monthly business review",
    freshnessHours: 16,
    definitionScore: 89,
    usage30d: 157,
    variancePct: 1.6,
    excelMismatchRate: 0.8,
    issueCount: 1,
    decisionCriticality: 5
  },
  {
    metric: "Bookings forecast accuracy",
    team: "Finance",
    owner: "FP&A",
    system: "Spreadsheet model",
    dashboard: "Forecast review",
    freshnessHours: 37,
    definitionScore: 77,
    usage30d: 109,
    variancePct: 5.7,
    excelMismatchRate: 7.5,
    issueCount: 6,
    decisionCriticality: 5
  },
  {
    metric: "Cash collection cycle",
    team: "Finance",
    owner: "Billing Ops",
    system: "Billing",
    dashboard: "Finance operations",
    freshnessHours: 23,
    definitionScore: 82,
    usage30d: 88,
    variancePct: 3.4,
    excelMismatchRate: 3.2,
    issueCount: 3,
    decisionCriticality: 3
  },
  {
    metric: "Support first response SLA",
    team: "Support",
    owner: "Support Ops",
    system: "Ticketing",
    dashboard: "Customer operations",
    freshnessHours: 10,
    definitionScore: 90,
    usage30d: 136,
    variancePct: 1.9,
    excelMismatchRate: 1.2,
    issueCount: 1,
    decisionCriticality: 4
  },
  {
    metric: "Escalation rate",
    team: "Support",
    owner: "Support Ops",
    system: "Ticketing",
    dashboard: "Customer operations",
    freshnessHours: 25,
    definitionScore: 80,
    usage30d: 97,
    variancePct: 3.6,
    excelMismatchRate: 2.6,
    issueCount: 4,
    decisionCriticality: 4
  },
  {
    metric: "Customer satisfaction",
    team: "Support",
    owner: "Customer Insights",
    system: "Survey platform",
    dashboard: "Voice of customer",
    freshnessHours: 49,
    definitionScore: 70,
    usage30d: 91,
    variancePct: 6.1,
    excelMismatchRate: 5.8,
    issueCount: 7,
    decisionCriticality: 4
  },
  {
    metric: "Case backlog age",
    team: "Support",
    owner: "Unassigned",
    system: "Ticketing",
    dashboard: "Customer operations",
    freshnessHours: 33,
    definitionScore: 73,
    usage30d: 82,
    variancePct: 4.8,
    excelMismatchRate: 4.7,
    issueCount: 5,
    decisionCriticality: 3
  },
  {
    metric: "Fulfillment cycle time",
    team: "Operations",
    owner: "Ops Analytics",
    system: "Operations database",
    dashboard: "Service delivery",
    freshnessHours: 14,
    definitionScore: 87,
    usage30d: 124,
    variancePct: 2.4,
    excelMismatchRate: 1.6,
    issueCount: 2,
    decisionCriticality: 4
  },
  {
    metric: "Implementation on-time rate",
    team: "Operations",
    owner: "Ops Analytics",
    system: "Project tracker",
    dashboard: "Service delivery",
    freshnessHours: 26,
    definitionScore: 79,
    usage30d: 101,
    variancePct: 3.9,
    excelMismatchRate: 3.1,
    issueCount: 4,
    decisionCriticality: 4
  },
  {
    metric: "Data handoff defect rate",
    team: "Operations",
    owner: "Data Operations",
    system: "Warehouse",
    dashboard: "Data quality review",
    freshnessHours: 12,
    definitionScore: 92,
    usage30d: 119,
    variancePct: 1.3,
    excelMismatchRate: 0.9,
    issueCount: 1,
    decisionCriticality: 4
  },
  {
    metric: "Manual adjustment volume",
    team: "Operations",
    owner: "Data Operations",
    system: "Spreadsheet model",
    dashboard: "Data quality review",
    freshnessHours: 53,
    definitionScore: 66,
    usage30d: 69,
    variancePct: 7.2,
    excelMismatchRate: 8.1,
    issueCount: 8,
    decisionCriticality: 3
  }
];
